kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.13
  commands:
  - uname -a
  - echo world
  - echo test1234
  - ls -al 
- name: publish
  image: plugins/docker
  commands:
  - uname -a
  - ls -al
  - whoami
  - pwd
  - mkdir ~/test
  #  commands:
  #  - ./twistcli
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nancom21/testpublic
#    repo: nancom21/kjn-test-drone3
    auto_tag: false
    auto_tag_suffix: drone-build
    tags:
      - kjn-drone-test-1.0
