kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.13
  commands:
  - echo world
  - echo test1234
- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: user1
    password:
      from_secret: docker_password
    repo: nancom21/kjn-test-drone3
    auto_tag: true
    auto_tag_suffix: drone-build
