kind: pipeline
type: docker
name: default

steps:
- name: test
  image: nginx:latest
  commands:
  - apt get
- name: build
  image: golang:1.13
  commands:
  - echo world
  - echo test1234
  - "go build -o ./myapp"
  - ./twistcli 
- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nancom21/kjn-test-drone3
    auto_tag: true
    auto_tag_suffix: drone-build
