kind: pipeline
type: docker
name: default

steps:
- name: build
  environment:
    TL_USER: twistcli
    TL_PASS: twistcli
    TL_CONSOLE_URL: https://52.78.4.73:8083
  image: golang:1.13
  commands:
  - uname -a
  - echo world
  - echo test1234
  - ls -al 
  - whoami
  - curl -k -u $TL_USER:$TL_PASS --output ./twistcli https://52.78.4.73:8083/api/v1/util/twistcli
  - chmod a+x ./twistcli
  - echo ===== Twistcli ready =====
  - ./twistcli --version
  
- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack_webhook
    channel: naver-kjn-drone
    #    username: nancom21@naver.com
    template: >
      {{#success build.status}}
        build {{build.number}} status: *{{build.status}}*
        build link: {{build.link}}
        build author: {{build.author}}
        build ref: {{build.ref}}
        build event: {{build.event}}
        build commit: {{build.commit}}
        build branch: {{build.branch}}
        build deploy: {{build.deployTo}}
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
      #http://plugins.drone.io/drone-plugins/drone-slack/
#- name: send
#  image: plugins/webhook
#  settings:
#    urls: https://52.78.4.73:8083/api/v1/coderepos/webhook/G0NmFXKHWfKK0S4_PlhywzqVaeo=

- name: publishhttps://github.com/nancom21/kjn-test-drone3/blob/main/.drone.yml
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nancom21/testpublic
#    repo: nancom21/kjn-test-drone3
    auto_tag: true
    auto_tag_suffix: drone-build2
    dockerfile: docker_files/Dockerfile.linux.amd64

- name: scanning
  image: debian:latest
  commands: 
  - ./twistcli --version
  - docker images
