kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.13
  commands:
  - uname -a
  - echo world
  - echo test1234
  - ls -al 
  - whoami
- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack_webhook
    channel: naver-kjn-drone
    #    username: nancom21@naver.com
    template: >
      {{#success build.status}}
        build {{build.number}} status: *{{build.status}}*
        build link: {{build.link}}
        build author: {{build.author}}
        build ref: {{build.ref}}
        build event: {{build.event}}
        build commit: {{build.commit}}
        build branch: {{build.branch}}
        build deploy: {{build.deployTo}}
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
#http://plugins.drone.io/drone-plugins/drone-slack/
- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nancom21/testpublic
#    repo: nancom21/kjn-test-drone3
    auto_tag: true
    auto_tag_suffix: drone-build
    dockerfile: /home/admin/drone/drone_user1/docker_files/Dockerfile.linux.amd64

